In [1]:
import numpy as np

In [18]:
%config ZMQInteractiveShell.ast_node_interactivity='all'
%pprint

Pretty printing has been turned ON


In [21]:
a = np.array([[1,2,3],[4,5,6]])
print("总共元素个数：" + str(a.size))
print(f"矩阵维度：{a.ndim}")
print(f"矩阵型状：{a.shape}")
print(f"矩阵类型：{a.dtype}")
print(f"所占字节数：{a.itemsize}") # 所占字节数
print(f"内存信息：{a.flags}") # 内存信息

# 数组的 dtype 为 int8(一个字节)
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

# 数组的 dtype 现在为 float64(八个字节) 
y = np.array([1,2,3,4,5], dtype = np.float64)
print (y.itemsize)

总共元素个数：6
矩阵维度：2
矩阵型状：(2, 3)
矩阵类型：int64
所占字节数：8
内存信息：  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

1
8


In [25]:
a = np.array([[1, 2], [3, 4]]) 
a
# make a copy
a.astype(np.float32)
a

array([[1, 2],
       [3, 4]])

array([[1., 2.],
       [3., 4.]], dtype=float32)

array([[1, 2],
       [3, 4]])

In [32]:
# 创建矩阵
x = np.empty([3,2], dtype =np.int) 
x

y = np.zeros((5,), dtype = np.int)
y

x = np.ones([2,2], dtype = int)
x

b = [(1,2,3),(4,5)]
a = np.asarray(b)
a

np.asarray([1, 2, 3,4]).reshape((2,2)) 

x = np.arange(5, dtype = float)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

array([0, 0, 0, 0, 0])

array([[1, 1],
       [1, 1]])

array([(1, 2, 3), (4, 5)], dtype=object)

array([[1, 2],
       [3, 4]])

array([0., 1., 2., 3., 4.])

In [33]:
np.logspace(0, 2, 5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [35]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [37]:
np.random.random((3,2,3))

array([[[0.77209002, 0.49133644, 0.12267235],
        [0.70076337, 0.24696731, 0.60648047]],

       [[0.9230859 , 0.31182973, 0.06532808],
        [0.2917098 , 0.06019575, 0.63095026]],

       [[0.30357795, 0.28679144, 0.36914515],
        [0.48659266, 0.44987747, 0.94548966]]])

In [40]:
np.arange(1,13).reshape((3,-1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
# 切片与索引
a=np.arange(10) #[0123456789] 
b = a[5]; c=a[:3]
b
c

a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (a[...,1]) # 第2列元素
print (a[1,...]) # 第2行元素
print (a[...,1:]) # 第2列及剩下的所有元素

5

array([0, 1, 2])

[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [48]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
x
y = x[[0,1,2], [0,1,0]]
y

array([[1, 2],
       [3, 4],
       [5, 6]])

array([1, 4, 5])

In [55]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]]) 
a
b = a[1:3, 1:3]
c = a[1:3, [1,2]]
d = a[...,1:]
b
c
d
x=np.arange(32).reshape((8,4)) 
x
x[[-4,-2,-1,-7]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[5, 6],
       [8, 9]])

array([[5, 6],
       [8, 9]])

array([[2, 3],
       [5, 6],
       [8, 9]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

array([[16, 17, 18, 19],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 4,  5,  6,  7]])

In [56]:
# 广播机制
a = np.array([[ 0, 0, 0], [10,10,10], [20,20,20], [30,30,30]])
b = np.array([1,2,3])
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [61]:
# 转置
a = np.arange(15)
# 返回的是源数据的视图(不会进行任何复制操作)
a.reshape((3,5)).T
a

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
arr = np.arange(15).reshape((3, 5)) 
np.dot(arr.T, arr)

arr = np.arange(24).reshape((2, 3, 4)) 
arr
# make a copy
a = arr.transpose((1, 0, 2))
a.shape

# make a copy
b = arr.swapaxes(1, 2)
b.shape

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(3, 2, 4)

(2, 4, 3)

In [71]:
# 常见的统计函数
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
a
print (np.amin(a,1))
print (np.amax(a, axis = 0))
print (np.mean(a, axis = 0)) #mean() 函数返回数组中元素的算术平均值。 print (np.std([1,2,3,4]))#标准差std = sqrt(mean((x - x.mean())**2)) print (np.var([1,2,3,4]))#方差mean((x - x.mean())** 2)

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

[3 3 2]
[8 7 9]
[4.33333333 5.         5.66666667]


In [74]:
# 排序、条件刷选函数
a = np.array([[3,7],[9,1]]) 
np.sort(a, axis = 0)

x = np.array([3, 1, 2]) 
np.argsort(x)

a = np.array([[30,40,70],[80,20,10],[50,90,60]])
a.shape
np.argmax(a, axis = 0)
np.argmax(a, axis = 1) 
np.argmin(a, axis = 1)

array([[3, 1],
       [9, 7]])

array([1, 2, 0])

(3, 3)

array([1, 2, 0])

array([2, 0, 1])

array([0, 2, 0])

In [77]:
# where函数
# np.where函数是三元表达式x if condition else y的矢量化版本，
# np.where() 函数返回输入数组中满足给定条件的元素的索引。
x = np.arange(9.).reshape(3, 3) 
x
y = np.where(x > 3)
y
print ('使用这些索引来获取满足条件的元素:') 
x[y]

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

使用这些索引来获取满足条件的元素:


array([4., 5., 6., 7., 8.])

In [79]:
arr = np.array([
    [1, 2, np.NaN, 4],
    [4, 5, 6, np.NaN],
    [7, 8, 9, np.inf],
    [np.inf, np.e, np.pi, 4]
])
arr

condition = np.isnan(arr) | np.isinf(arr)
# 条件，替换纸，矩阵
np.where(condition, 0, arr)

array([[1.        , 2.        ,        nan, 4.        ],
       [4.        , 5.        , 6.        ,        nan],
       [7.        , 8.        , 9.        ,        inf],
       [       inf, 2.71828183, 3.14159265, 4.        ]])

array([[1.        , 2.        , 0.        , 4.        ],
       [4.        , 5.        , 6.        , 0.        ],
       [7.        , 8.        , 9.        , 0.        ],
       [0.        , 2.71828183, 3.14159265, 4.        ]])

In [83]:
# numpy.nonzero() 函数返回输入数组中非零元素的索引。
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
a
print ('调用 nonzero() 函数:') 
x = np.nonzero (a)
x
a[x]

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

调用 nonzero() 函数:


(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))

array([30, 40, 20, 10, 50, 60])

In [86]:
# np.unique函数的主要作用是将数组中的元素进行去重操作(也就是只保存不重复的数据)
# 打平，排序，去重
A=[1,2,2,5,3,4,3]
a = np.unique(A)
a

B=(1,2,2,5,3,4,3)
b= np.unique(B)
b

C= [['fgfh','asd'],['fgfh','asdfds'],['wrh', 'edg']]
c= np.unique(C)
c

array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

array(['asd', 'asdfds', 'edg', 'fgfh', 'wrh'], dtype='<U6')